{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jwoglom.pumpx2",
    "module": "pumpx2-messages",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pumpx2-messages-1.1.5.jar",
          "url": "pumpx2-messages-1.1.5.jar",
          "size": 277914,
          "sha512": "e95dfec23a7f8f975b3af944c3b2d0568a1dc5b078416b5c75807c2c43ce88ccfdbe1fe4690e1e1ed8db38697a81b71c2b6aaf7ac8ccea6dd49a762b4103ccdb",
          "sha256": "7a780a917d49b2539459eb2b4eaaf595b8eae367dfb91e93a67e300422b0b85f",
          "sha1": "b38ad00729fd68753df83a1242030c1eb8cf47bf",
          "md5": "56b0f39e553c1f8888eb4124844c8a3e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.jwoglom.pumpx2",
          "module": "pumpx2-shared",
          "version": {
            "requires": "1.1.5"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "pumpx2-messages-1.1.5.jar",
          "url": "pumpx2-messages-1.1.5.jar",
          "size": 277914,
          "sha512": "e95dfec23a7f8f975b3af944c3b2d0568a1dc5b078416b5c75807c2c43ce88ccfdbe1fe4690e1e1ed8db38697a81b71c2b6aaf7ac8ccea6dd49a762b4103ccdb",
          "sha256": "7a780a917d49b2539459eb2b4eaaf595b8eae367dfb91e93a67e300422b0b85f",
          "sha1": "b38ad00729fd68753df83a1242030c1eb8cf47bf",
          "md5": "56b0f39e553c1f8888eb4124844c8a3e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pumpx2-messages-1.1.5-all.jar",
          "url": "pumpx2-messages-1.1.5-all.jar",
          "size": 6556754,
          "sha512": "4a8d574abeba5bd885ff06443f1d3d321b178f0f87475cb15f3ad3916a1cf99afec7d9d6fd159db185f5292de7dab7e6435f0f8fb4b677e2803de5d4326f0b08",
          "sha256": "114442dadac7efd06c1ca2240622f3bc324c67be5f7868aed4ba855bcabf8b98",
          "sha1": "504de922eb2d7ac550d19966613c9e12c94cd882",
          "md5": "2df1137d51c81866b77aab015b481052"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pumpx2-messages-1.1.5-sources.jar",
          "url": "pumpx2-messages-1.1.5-sources.jar",
          "size": 162883,
          "sha512": "3db528e3f0356c9665f5090969082a242a75fecd2e790e722bf7dafd015da321bc554c99590a2f8cfe5d91933ecba75907030be7f4e8faf90052b3ca147c1780",
          "sha256": "9fddd4f79fc37bcd99825ccf3f2f1c3550c477c33fe6f352329634390fbca18e",
          "sha1": "d6be280e2b5d47c0ddb6d96ab6a71630609e8947",
          "md5": "55bd0ae2e0dd2e53e04bc46a7fe11ed6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pumpx2-messages-1.1.5-javadoc.jar",
          "url": "pumpx2-messages-1.1.5-javadoc.jar",
          "size": 1226285,
          "sha512": "26851ed98c3e0863399bbbb8282b179f294bb87d14dd4174333be97ced43fc2b833a9cd6929b5fffb8437bbb2ab51471dcf243df9d4d448b5ecbae4b877af155",
          "sha256": "5cb0f6890de1dfc1db9a2dfe32e10a945a6ea645ad0e7312194216dadfa3e267",
          "sha1": "f5c458b1a2d5911fb865ece7e70e9e76c9db90fc",
          "md5": "2d025115ef64af9c63494e9b6a465de4"
        }
      ]
    }
  ]
}
