{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jwoglom.pumpx2",
    "module": "pumpx2-shared",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pumpx2-shared-1.1.0.jar",
          "url": "pumpx2-shared-1.1.0.jar",
          "size": 7127,
          "sha512": "d78d3cbafea50f9676f907e3269784bf712afc1ceeb0860b732d3c8a4376636abb6be15c39924b905f9954711815d3662bbed5b210d0a65a57427265f9fe5afc",
          "sha256": "5ce6befd759abfa71fa21f6e19c6645d8a45ddae6b20292420ec6bcddacb07d3",
          "sha1": "4df49641e2385b303eb6cee6b1950a8f573e8ca5",
          "md5": "dabe428db6f6982ce33325b27e003ca5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.champeau.openbeans",
          "module": "openbeans",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "pumpx2-shared-1.1.0.jar",
          "url": "pumpx2-shared-1.1.0.jar",
          "size": 7127,
          "sha512": "d78d3cbafea50f9676f907e3269784bf712afc1ceeb0860b732d3c8a4376636abb6be15c39924b905f9954711815d3662bbed5b210d0a65a57427265f9fe5afc",
          "sha256": "5ce6befd759abfa71fa21f6e19c6645d8a45ddae6b20292420ec6bcddacb07d3",
          "sha1": "4df49641e2385b303eb6cee6b1950a8f573e8ca5",
          "md5": "dabe428db6f6982ce33325b27e003ca5"
        }
      ]
    }
  ]
}
