{
  "formatVersion": "1.1",
  "component": {
    "group": "com.jwoglom.pumpx2",
    "module": "pumpx2-shared",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pumpx2-shared-1.1.4.jar",
          "url": "pumpx2-shared-1.1.4.jar",
          "size": 7835,
          "sha512": "724b5aeef0261ddad2a7cb3c40386c3847d5401f488fb20bb7b7ccbd03cbded75276797a44c2d07c41105001865e8132a1e2e54d53374d0c1ab99b4adaf37734",
          "sha256": "96b8a69a2b443ad2e348ffe767a5d8ea4bbd5bfadd6129b1c24a527780041116",
          "sha1": "a516b4046d0f35005cc16da8484df8fce7e358c8",
          "md5": "36ef735ec0e6e8c41b828cd32ba7912f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.champeau.openbeans",
          "module": "openbeans",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.15"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.0.1-android"
          }
        }
      ],
      "files": [
        {
          "name": "pumpx2-shared-1.1.4.jar",
          "url": "pumpx2-shared-1.1.4.jar",
          "size": 7835,
          "sha512": "724b5aeef0261ddad2a7cb3c40386c3847d5401f488fb20bb7b7ccbd03cbded75276797a44c2d07c41105001865e8132a1e2e54d53374d0c1ab99b4adaf37734",
          "sha256": "96b8a69a2b443ad2e348ffe767a5d8ea4bbd5bfadd6129b1c24a527780041116",
          "sha1": "a516b4046d0f35005cc16da8484df8fce7e358c8",
          "md5": "36ef735ec0e6e8c41b828cd32ba7912f"
        }
      ]
    }
  ]
}
